id: c70a2796-c865-42f0-b6d3-9ad9b0af6e9a
auth:
  type: basic
  basic:
    - type: string
      value: "{{password}}"
      key: password
    - type: string
      value: "{{username}}"
      key: username
variables:
  - key: city
    value: lagos
    type: default
  - key: country
    value: nigeria
    type: default
  - key: username
    value: empty
    type: default
  - key: password
    value: empty
    type: default
prerequest: |
  // Just for testing
  console.log('Collection: Before the request is executed');
tests: |-
  // Just for testing
  console.log('Collection: After the request was executed');
